type Mutation {
  fetchTranscript (
    url: String!
  ): FetchTranscriptResponse
}

type Mutation {
  summarizeVideo (
    url: String!
    videoId: String!
    videoTitle: String!
    channelTitle: String!
    duration: Int!
    transcript: String!
  ): SummarizeVideoResponse
}

type FetchTranscriptResponse {
  videoId: String!
  videoTitle: String!
  channelTitle: String!
  duration: Int!
  transcript: String!
}

type SummarizeVideoResponse {
  id: String!
  videoTitle: String!
  channelTitle: String!
  thumbnailUrl: String!
  duration: Int!
  summary: String!
  modelUsed: String
}
